### ISSUE TITLE
OpenWebif recordings list broken

### ISSUE THREAD

**Issue by JLahtin** [oe-alliance/OpenWebif#13]
The recording list in the OpenWebif interface of my Vu+ Ultimo4K doesn't work. When I select the recordings list in the main menu on the left, the list never appears, the spinner just keeps rotating. 
I don't know whether it matters, but I have the interface language set to Finnish and OpenWebif Theme original and the new interface unchecked.
There have been so many OpenVix update releases lately that I don't know which one was the first with this problem, but I think I already saw it in at least two versions before I updated to 6.3.007 on Thursday.

I normally use Seamonkey, but just checked that the problem can be also seen with Firefox.

**Comment by jbleyel** [comment]
Please provide more details.
We need crash log / debug log.
Is this problem on each directory?

**Comment by JLahtin** [comment]
[Enigma2_debug_2023-04-11_18-16-06.log](https://github.com/oe-alliance/OpenWebif/files/11202207/Enigma2_debug_2023-04-11_18-16-06.log)

**Comment by JLahtin** [comment]
I turned debug logging off and on thrhough OpenWebif, and clicked the recordings link, turned debug logging off again, newest log attached.
It happens when I click the recording list, doesn't show even the main directory, so I can't test if it happens in other directories as well when I don't get the directory listing.

**Comment by jbleyel** [comment]
This is the error message:


File "/home/vix/6.3/builds/openvix/release/vuultimo4k/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-extensions-openwebif/enigma2-plugin-extensions-openwebif-gitAUTOINC+80f6767709-r0/image/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/views/ajax/movies.py", line 130, in respond

NameMapper.NotFound: cannot find 'split' while searching for 'split'

I have never seen that error before.

There is probably a file or directory in your recording directory which causes that error.
But that’s only a guess.

**Comment by jbleyel** [comment]
Please delete these 2 files on your Box and try again if exits .

usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/views/ajax/movies.py

usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/views/ajax/movies.pyc


I need the debug log.

**Comment by jbleyel** [comment]
Don’t delete this file!!!!

usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/views/ajax/movies.tmpl

**Comment by JLahtin** [comment]
There was no movies.py or movies.tmpl in the OpenWebif/controllers/views/ajax, I moved movies.pyc from there to /tmp (not totally deleting it yet). It didn't help. 
Maybe I should create a temporary subdirectory and move the recordings there (few at a time) to see if that helps. 
A new debug log attached.
[Enigma2_debug_2023-04-12_16-27-23.log](https://github.com/oe-alliance/OpenWebif/files/11211951/Enigma2_debug_2023-04-12_16-27-23.log)

**Comment by jbleyel** [comment]
You need to download the tmpl file from here 

https://github.com/oe-alliance/OpenWebif/blob/main/plugin/controllers/views/ajax/movies.tmpl

And put this here ->

usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/views/ajax/movies.tmpl


Then open the recordings in Openwebif and then send the debug log.

**Comment by JLahtin** [comment]
A new debug log after downloading movies.tmpl
[Enigma2_debug_2023-04-12_23-30-14.log](https://github.com/oe-alliance/OpenWebif/files/11215777/Enigma2_debug_2023-04-12_23-30-14.log)

**Comment by jbleyel** [comment]
Please provide the default path of your recordings.
This should be normally /media/hdd/movies

**Comment by JLahtin** [comment]
It is /media/hdd/movie , no 's' in the end.

**Comment by jbleyel** [comment]
Please open this link in the browser:

`http://ip of your box/ajax/movies?dirname=/media/hdd/movie`

And check the debug log if there is an error like this:
NameMapper.NotFound: cannot find 'split' while searching for 'split'

**Comment by jbleyel** [comment]
Another test.

Please open this link in browser:

`http://ip of your box/api/movielist?dirname=/media/hdd/movie
`
And provide the last block of the json result after all recordings.

Must be like this:

```
 ],
 "bookmarks": [
 .....
 ],
 "directory": "/media/hdd/movie/",
 "recursive": false
}

```

**Comment by JLahtin** [comment]
The ajax/movies?dirname=/media/hdd/movie showed the recording list without any errors in the debug log (not formatted as pretty as usually, but I suppose that was expected).
The latter had the json result ending like this:
],
 "bookmarks": [
  ".Trash",
  "astan",
  "jemma",
  "jukan",
  "simpsons"
 ],
 "directory": "/media/hdd/movie/",
 "recursive": false
}

Hmm, I don't THINK I have changed the recording directory name myself, but I can't rule out accidental slips of fingers..

**Comment by JLahtin** [comment]
I made an experiment by symlinking the 'movie' directory as 'movies'
(ln -s movie movies) and after that OpenWebif showed the recording list as expected.
