### ISSUE TITLE
EPG today shows data from yesterday if older epg data is present

### ISSUE THREAD

**Issue by retoch44** [oe-alliance/OpenWebif#24]
Affected user interface (delete as appropriate):
This bug occurs in both the Modern and Classic web interfaces.

Describe the bug / Actual behaviour:
I configured OpenATV to save older EPG data for 1440 minutes (max). The EPG in OpenWebif for the present day now shows data from yesterday (see picture), following days show correct data. EPG on TV shows always correct data. If save older EPG data is set to 0, EPG for the present day works in OpenWebif.

Has this issue started to happen just recently?
Noted that since upgrading from OpenATV 6.4 to 7.x some month ago. 

OS: OpenATV
Version 7.3 Build 2023-08-18

Browser firefox, vivaldi / windows
Version newest

Additional context
OWIF 2.0.7
Build: 2.0.7-git106+c2e44ad-r0

![2023-08-19-14 48 22-192 168 0](https://github.com/oe-alliance/OpenWebif/assets/142671411/b7aa0be2-bec0-437a-a02e-6cd59d2a0f69)

**Comment by retoch44** [comment]
Thanks. I copied the changed services.py to my box, restartet it and now the current day begins with data from yesterday late night, last broadcasts before the day changes. Shouldn't it show the broadcasts of the actual time?

**Comment by jbleyel** [comment]
If you have history EPG then you can also see them, this is by design and by request from other user.
If you don't like that, then we need to add a new setting to hide history EPG data.

**Comment by retoch44** [comment]
Okay, but this feature (jump to actual time of current day in epg view even if older epg data is present) worked for years in version 1.x of OpenWebif, if I remember right. Is this depending on Enigma2-version?

**Comment by jbleyel** [comment]
The history data display is a new feature in version 2.x.
I have never seen old epg data in version 1.x as I remember.

**Comment by retoch44** [comment]
Ah yes, I used to look at old epg data on TV only and never tried to use it in Owif v1, but then wondered about different behaviour in v2.

Then I have to do a feature request :-) - please add an additional toggle "In EPG view automatically jump to actual time & date, if older EPG data is available".

**Comment by jbleyel** [comment]
This is not that easy. I'm thinking about to add a new setting called "Don't show history EPG data".

**Comment by retoch44** [comment]
Thanks, that should have the same effect.
