### ISSUE TITLE
OpenWebif broken after recent update

### ISSUE THREAD

**Issue by wedebe** [oe-alliance/OpenWebif#28]
*!* Before you log an issue, have you updated to the most recent version? It's possible the issue may have already been fixed.
Using latest 2023-10-14 image - broken
Using image 2023-10-13 - broken

**Affected user interface (delete as appropriate):**
Entire UI - homepage returns 404

**Describe the bug / Actual behaviour:**
Go to OWIF url:
```
Error 404: Not found

The requested page doesn't exist.
```

**Expected behaviour:**
OWIF UI should load

**Has this issue started to happen just recently?**
Yes,
Using latest 2023-10-14 image - broken
Using image 2023-10-13 - broken

**To reproduce:**
Steps to reproduce the behaviour:
1. See above

**Screenshots**
```
13:49:25.1526 [SEC] invalidate current switch params
13:49:25.2169 [SEC] tuner 0 sendDiseqc: e00000(DiSEqC reset)13:49:25.2169 [eDVBFrontend] [SEC] diseqc ioctl duration: 64 ms13:49:25.2276 [OpenWebif] ERROR! Template not found for page 'b'/''
13:49:25.2290 "::ffff:192.168.43.154" - - [16/Oct/2023:12:49:22 +0000] "GET / HTTP/1.1" 404 129 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"
13:49:25.2300 [eDVBFrontend] [SEC] tuner 0 sleep 50ms
```

Specifically:
`[OpenWebif] ERROR! Template not found for page 'b'/''`

**Image (please complete the following information):**
 - OS: OpenATV
 - Version 7.3

**Desktop (please complete the following information):**
ALL

**Additional context**
Also note the lack of line breaks between modules in the debug logging above.

**Comment by jbleyel** [comment]
This is already fixed.
