### ISSUE TITLE
zap not working for a 4097 stream at modern interface

### ISSUE THREAD

**Issue by erich-b** [oe-alliance/OpenWebif#32]
see thread in V1 (https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/1578). Issue exists identically in current version 

If you click the button with the little remote on it, zapping works.
If you click the channel-name or the picon the previous channel stops playing (audio and also video if it was a tv-channel) but zapping to the new channel does not happen

**Comment by jbleyel** [comment]
Is this a Firefox only issue?
Or do you have that in any browser?

**Comment by erich-b** [comment]
happens in any browser... i just tried it again in Chrome.
cause seems to me a missing character in the URL that is called.
Got the called URLs from the development tools from Chrome and Firefox (identical in both cases).
Working (clicking on the button with the remote)
http://<boxip>/api/zap?sRef=4097%3A0%3A2%3A3%3A1%3A3%3A0%3A0%3A0%3A0%3Ahttps%253a//stream.radiotechnikum.at/RADIOONE%3ARadio%20ONE&_=1699602112617
Not-Working (clicking on the station logo or name):
http://<boxip>/api/zap?sRef=4097%3A0%3A2%3A3%3A1%3A3%3A0%3A0%3A0%3A0%3Ahttps%3A//stream.radiotechnikum.at/RADIOONE%3ARadio%20ONE&_=1699602112618

**Comment by erich-b** [comment]
Thx for the fast fix, but I have to re-open it.
Issue has inverted now...
Now clicking on the station logo and the title works, but the URL behind the remote-symbol-button is now broken, because the replace seems to happen twice.

Logo or stationname: http://x.x.x.x/api/zap?sRef=4097%3A0%3A2%3A3%3A1%3A3%3A0%3A0%3A0%3A0%3Ahttps%253a//stream.radiotechnikum.at/RADIOONE%3ARadio%20ONE&_=1699988881961
remote-symbol-button: http://x.x.x.x/api/zap?sRef=4097%3A0%3A2%3A3%3A1%3A3%3A0%3A0%3A0%3A0%3Ahttps%25253a//stream.radiotechnikum.at/RADIOONE%3ARadio%20ONE&_=1699988881962

(Serviceline is the same as in my previous post)

**Comment by jbleyel** [comment]
please try this:

[channels.tmpl.zip](https://github.com/oe-alliance/OpenWebif/files/13355216/channels.tmpl.zip)

**Comment by erich-b** [comment]
sorry, that's too much indepth unix for me. I got your previous fix with the normal update on my box, but have no idea how to get a .tmpl into a .pyc file and have it properly replaced/installed on the box

**Comment by jbleyel** [comment]
Delete channels.pyc in this folder on your box:

`/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/views/responsive/ajax
`

and copy the channels.tmpl into this folder

**Comment by erich-b** [comment]
didn't expect it to be that easy...

It works with that file. All 3 methods (logo, station name and remote-symbol) are switching to 4097 radio channels properly.

Thx a lot for your help!

**Comment by jbleyel** [comment]
Please try again.
The Picon click was wrong in the last version. 
[channels.tmpl.zip](https://github.com/oe-alliance/OpenWebif/files/13366401/channels.tmpl.zip)

**Comment by erich-b** [comment]
Still working for me.
