### ISSUE TITLE
/web/signal returns nothing when signal finder is open

### ISSUE THREAD

**Issue by sys2065** [oe-alliance/OpenWebif#35]
Currently /web/signal or /api/signal is not very useful, because it only works after some channel is tuned. But it needs to work also in signal finder.

Problem is in info.py
```
service = session.nav.getCurrentService()
	if service is None:
		return inf
```
Obviously it's not possible to use getCurrentService() and this needs to be implemented differently.

In any case, see attached info.py / diff for one way of fixing this.

It's not a complete solution, missing is for example all value conversions for different receivers (check frontend.cpp), but it's working fine in my Octagon SF8008 supreme. (Tested openatv7.3/openvix6.5, transferring info.py file to /usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/models/)

Also, all new code goes to "if service is None" block, so it would be easy to add something like this without breaking anything.
[info.zip](https://github.com/oe-alliance/OpenWebif/files/14754600/info.zip)
[signal.txt](https://github.com/oe-alliance/OpenWebif/files/14754606/signal.txt)

**Comment by jbleyel** [comment]
What’s the exact purpose to call the api until the signal finder is open?
Is that really necessary?

**Comment by sys2065** [comment]
There are many reasons why this is useful, but for example when you are installing new dish.
First you open signal finder screen in your E2-box and enter some frequency there. Then you open <boxip>/api/signal in your phone.
Without this fix you don't see any signal in your phone..

**Comment by jbleyel** [comment]
Understood. I will check that.

**Comment by sys2065** [comment]
"If you change that, how will OpenWebIf know which tuner to get the reading from?"

I did not change that, only added alternative way to get signal values in case there is no current service.

You can check attached signal.txt diff. I admit that's not the best way to get active tuner, but I could not come up with anything better quickly or easily. But of course if there are other suggestions? In any case it works for me and just wanted to share this. There are ways to improve..

**Comment by sys2065** [comment]
Yes, but then it returns values from first active tuner it finds. But open for other suggestions

**Comment by Huevos** [comment]
Well how do you know that is the tuner you are interested in? Might be receiving from a completely different satellite.

**Comment by sys2065** [comment]
Lets say there are three tuners A,B,C. If signal finder screen is open and C is selected, then A and B are usually not in use and it skips them.
If A or B is currently used for recording for example, then they are going to be active, but I would know this.

Closing this won't make issue disappear..

**Comment by jbleyel** [comment]
The signal api only supports one tuner.
The active tuner of the current active channel and now also the active tuner of the signal finder.

All other things what you want needs a complete refactoring and you should describe your feature request more detailed because my crystal ball is currently not working.

**Comment by sys2065** [comment]
Ok, I missed that you already fixed this, and it does work now, thank you
