### ISSUE TITLE
Processing Failed

### ISSUE THREAD

**Issue by BrianG61UK** [oe-alliance/OpenWebif#4]
Openwebif I'm running is from self built OpenViX 6.2.012.007 Developer.

This bug occurs in the `Classic` web interface.

I can't get anything except "Processing Failed" in my web browser.

Issue has appeared only in version I built today and version I built 2 days ago.

Open IP address of OpenViX box in browser.
"Processing Failed" appears.

OS: OpenViX 6.2.012.007 Developer

Browser Firefox 107.0 or Chrome 107.x.x.x.

Result from debug traceback in Browser:

web.Server Traceback (most recent call last):
builtins.TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
/usr/lib/python3.10/site-packages/twisted/web/server.py:227 in process
226
227
228
/usr/lib/python3.10/site-packages/twisted/web/server.py:292 in render
291
292
293
/home/openvixbuilder/openvix/5.1/build-enviroment/builds/openvix/developer/h7/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-extensions-openwebif/enigma2-plugin-extensions-openwebif-gitAUTOINC+4e74b25973-r0/image/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py:230 in render
229
230
231
/home/openvixbuilder/openvix/5.1/build-enviroment/builds/openvix/developer/h7/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-extensions-openwebif/enigma2-plugin-extensions-openwebif-gitAUTOINC+4e74b25973-r0/image/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/base.py:293 in prepareMainTemplate
292
293
294
/home/openvixbuilder/openvix/5.1/build-enviroment/builds/openvix/developer/h7/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/enigma2-plugin-extensions-openwebif/enigma2-plugin-extensions-openwebif-gitAUTOINC+4e74b25973-r0/image/usr/lib/enigma2/python/Plugins/Extensions/OpenWebif/controllers/models/info.py:199 in getInfo
198
199
200
builtins.TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**Comment by BrianG61UK** [comment]
I'm closing this for now because the OpenViX team say they have fixed it on their end.

**Comment by Huevos** [comment]
It was this: https://github.com/oe-alliance/OpenWebif/commit/ff98faa7b38edfe3cedfdd06f271775e01f529c9#diff-d70535c60e5806636b4f7e10820fb55ee4f77c360e2538f06bb7c421e35480fdR298

That variable is set in openatv enigma. It doesn't come from BoxInfo.
