### ISSUE TITLE
"Add timer" not working (modern and classic interfaces)

### ISSUE THREAD

**Issue by OlivierV78** [oe-alliance/OpenWebif#5]
**Affected user interface (delete as appropriate):**
This bug occurs in *both* the `Modern` and `Classic` web interfaces.

**Describe the bug / Actual behaviour:**
Not show channels on Add Recording (either form Favorite or Last Scanned)

**Expected behaviour:**
Show all channels

**Has this issue started to happen just recently?**
If yes, roughly when did it last work fine for you?

**To reproduce:**
Go to the timer entry and try to add a timer : not possible to choice the channel

**Screenshots**
![Screenshot_20221231_181029](https://user-images.githubusercontent.com/22917586/210150987-7be91990-ccc0-44b5-b592-902280ecdbf9.png)

**Image (please complete the following information):**
Openatv 7.2

**Desktop (please complete the following information):**
Firefox 108.0

**Additional context**
Issue already give here since august but no solution : https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/issues/1541
Works with Chrome but note Firefox

**Comment by jbleyel** [comment]
Sorry for the delay!

There is probably no real solution if you have a big channel list in your bouquets.

You can delete and cleanup unused bouquets and try again.

Or you find a way to increase the local storage memory size setting in Firefox.

**Comment by OlivierV78** [comment]
Thank your for answer.
I tried again with firefox today and there is no bug anymore.
Issue closed.
