### ISSUE TITLE
/web/epgbouquet does not behave the same as in Version 1 API - causing issues.

### ISSUE THREAD

**Issue by original-birdman** [oe-alliance/OpenWebif#8]
This bug occurs in *both* the `Modern` and `Classic` web interfaces.

A call to:
   /web/epgbouquet?bref=<<a valid bRef>>
returns the **entire** EPG for that bouquet.

In version 1 it would only return the EPG contents at a single point in time (teh optional time parameter being when you want this to be, and default is "now). So there is no endTime parameter either.

 /web/epgbouquet now behaves exactly the same as /web/epgmulti.

This is causing a problem for things such as the dreamDroid Android app, which is using this call to get the service entries in bouquet. Instead of getting a quick repsonse it is taking >30s to get a >7MB response for a bouquet with 72 services in it.

I would expect this to replicate how the function behaved in the version 1 code (at https://github.com/E2OpenPlugins/e2openplugin-OpenWebif).

At the same time "dummy" services in the bouquet _(i.e._ those  added to get the required service number) are now being returned with an e2eventservicename of "&amp;lt;n/a&amp;gt;" (<n/a>) rather than being ignored and having no entry returned at all.

**Has this issue started to happen just recently?**
Yes. It happened when OpenVix switched to using the version 2 code.

**Comment by jbleyel** [comment]
/web/epgbouquet and /web/epgmulti is 100% the same.
Someone has created this issue in version 1.x .. and I have taken this to 2.0.

**Comment by original-birdman** [comment]
It is different in version 1 (or was)

**Comment by original-birdman** [comment]
To return the correct timespan just set endTime to beginTime.

But also need to remove the n/a data in the output.

**Comment by original-birdman** [comment]
The API documentation is quite specific as to what each should do:

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/wiki/OpenWebif-API-documentation#epgbouquet

**Comment by jbleyel** [comment]
I think this commit is the problem:

https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/28b85ed6f6f388c876186fc19ef882748e0abc20#diff-68fc95a20d23adada2cdf72324698e13b5cebb83c9f36e061b664e3087bb6aef

**Comment by original-birdman** [comment]
Yes. But its a bug.  Better not to copy bugs....

**Comment by jbleyel** [comment]
Please try
endtime = None 
in line 1444

**Comment by jbleyel** [comment]
I think this issue is not new because the involved code has no changes last year.
endtime = -1 or endtime = None has no effect.

**Comment by jbleyel** [comment]
Are you sure that the current version 1.x is correct?

**Comment by Huevos** [comment]
I doubt current 1.x is correct but only just been noticed.

**Comment by jbleyel** [comment]
1.x has the same bug

**Comment by original-birdman** [comment]
Setting `endTime` to 0 (or -1 - but 0 makes more sense as I think it's an extent, rather than an actual end time). Just tested it.

Can't figure out where the "n/a" is being generated - these entries should just be skipped.

**Comment by original-birdman** [comment]
The "n/a" is being added by `lookupEvent()` in `epgcache.cpp`.

I can get this removed by checking for service type in `getBouquetEpg()` (in `models/services.py`) before appending to the query and removing non-relevant types.
```
        for service in services.getContent('S'):
                stype = service.split(":", 3)
                if stype[1] == "64":    continue    # Bouquet header
                if stype[1] == "832":   continue    # Dummy number-padding entry
                query.append((service, 0, begintime, endtime))
```
There may be others ("320"?).
With this, **and** the `endTime` fix, all works as it used to.

**Comment by jbleyel** [comment]
This is an api change or has someone removed this filter?

**Comment by Huevos** [comment]
> The "n/a" is being added by `lookupEvent()` in `epgcache.cpp`.
> 
> I can get this removed by checking for service type in `getBouquetEpg()` (in `models/services.py`) before appending to the query and removing non-relevant types.
> 
> ```
>         for service in services.getContent('S'):
>                 stype = service.split(":", 3)
>                 if stype[1] == "64":    continue    # Bouquet header
>                 if stype[1] == "832":   continue    # Dummy number-padding entry
>                 query.append((service, 0, begintime, endtime))
> ```
> 
> There may be others ("320"?). With this, **and** the `endTime` fix, all works as it used to.

This is a wrong approach.

These are flags.

eServiceReference.isMarker=64

832 is just 64 with other flags. Look:

```
>>>
>>> 832 & 64
64
>>>
```

So you need to import eServiceReference and check against the respective flags. e.g.

`if int(stype[1]) & (eServiceReference.isDirectory | eServiceReference.isMarker | eServiceReference.isGroup):    continue`

**Comment by jbleyel** [comment]
I have no intention to do that, because this is an api change an may break some 3rd party tools.
Except someone has removed this filter.

**Comment by jbleyel** [comment]
I have checked version 0.x and there is no filter.

**Comment by original-birdman** [comment]
>>> because this is an api change

It is **not** an API change.

It is reverting to the original (and documented - see above) API.

The code you have implemented is _already breaking things_!

Don't know why there were no n/as previously, but they've only started showing up recently and they should not be there.

**Comment by original-birdman** [comment]
>So you need to import eServiceReference and check against the respective flags. e.g.
>
> if int(stype[1]) & (eServiceReference.isDirectory | eServiceReference.isMarker | eServiceReference.isGroup):    continue
>
> And because you are now using the correct flags with explanatory names you don't need to add "helpful" comments.

Whereas I agree that checking the bit pattern makes sense, that code _cannot_ be correct and 320 (== 0x0140) only has 2-bits set, so must fail a test against any 3-bits being set, but it needs to pass the test.

**Comment by original-birdman** [comment]
PS: Github says I'm receiving notifications as I authored the thread - but I'm not actually getting any....

**Comment by original-birdman** [comment]
I (think) I can see where the "n/a" crept in.

The V2 code uses:
```
epgEvents = epg.getBouquetENowNextEpg(bqRef, begintime, endtime)
```
to get the events, whereas the V1 code does not.
Or at least it does not do so now. It did sort-of - it actually called `getBouquetEevents`) until Sep 9, 2022 when this revert:
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif/commit/b9e90b19d397758369dcbe7d8b1a7bb54b5b66c1
(by jbleyel) sent it back to what it had been, which was a self-contained loop.

**Comment by jbleyel** [comment]
Yes . V1 and V2 is different.
Let me check why lookupEvents is not working as expected

**Comment by jbleyel** [comment]
https://github.com/oe-alliance/OpenWebif/commit/f68a41756d5eb1b1279069dd33994dfaaaeb15d6

**Comment by original-birdman** [comment]
You seem to continue to ignore the fact that the `epgbouquet` and `epgmulti` codes are the same, when they are meant to be different.
`epgbouquet` _should have no_ `endTime` _parameter_. This is documented. It is the equivalent of setting `endTime` to 0 (**not** to -1 as that means "get everything in the cache").

**Comment by jbleyel** [comment]
The extra parameter endTime has no effect until you don't set it.
So what's the problem?
The documentation is old and needs to maintain.

**Comment by jbleyel** [comment]
small update

https://github.com/oe-alliance/OpenWebif/wiki/OpenWebif-API-documentation#epgbouquet

**Comment by original-birdman** [comment]
> The extra parameter endTime has no effect until you don't set it.
So what's the problem?

The problem is that existing code does not set it and expects it to do what it is documented ot do, and what it had been doing for years until recently.

> The documentation is old and needs to maintain.

But the documentation is correct and reflects how it has been used historically.

**Comment by original-birdman** [comment]
> small update
>
> [oe-alliance/OpenWebif/wiki/OpenWebif-API-documentation#epgbouquet](https://github.com/oe-alliance/OpenWebif/wiki/OpenWebif-API-documentation#epgbouquet)

That is totally useless!!!!!

All that does is make `epgboquet` the same as `epgmulti`.

Stop treating the documentation as wrong.  It is the current **CODE** which is wrong. It is already causing problems in long-existjng software!

**Comment by original-birdman** [comment]
Why is this marked as closed???

It's still causing problems for existing software!!!!

**Comment by original-birdman** [comment]
If you insist on giving `epgbouquet` an `endTime` parameter (which it never did) then set the default to 0 (just get "now") with `epgmulti` setting the default to -1 (get everything that is in the cache).

**Comment by jbleyel** [comment]
I‘m confused.
The endTime parameter is new and optional. 
There is no endTime parameter in the old documentation.
The default is None and not -1.

**Comment by original-birdman** [comment]
> I‘m confused.

Clearly

> The endTime parameter is new and optional. 

But why? `epgmulti` was the call to make using an `endTime` parameter.

> There is no endTime parameter in the old documentation.

Correct. And there was no  `endTime` parameter in the call in the code _either_.  It is the addition of this which is causing the problem with the amount of the data being returned.
(The "n/a" inclusion is because the new search code differs from the old).

>  The default is None and not -1.

The default should be 0, meaning a zero time extent. Somewhat clearer than None.
 
> I get only now events if i don’t use the parameter. And this is exactly what we had before.

It is **not** what was happening when I opening this Bug Issue. You seemed to be concentrating on reproducing code that was already bugged, and ignoring documentation which was clear as to how the API should work.
You were talking about the `endTime` parameter when there is no need for this call to _have_ such a parameter (it's meant to get the EPG at a single point in time) and it has never has such a parameter in the past. So if anyone should be confused it's me.

It's also unclear as to what has happened to the (erroneous) "n/a" entries.

**Comment by jbleyel** [comment]
Have you tested my last commit?
Probably not.

**Comment by jbleyel** [comment]
If the last change is also wrong than give me more info how to reproduce the issue.

**Comment by original-birdman** [comment]
Since you continue to mention that `epgbouquet` needs an `endTime` parameter (which it doesn't) I wasn't aware that you'd made any change in that area.

I'll try the latest `epg.py`, `services.py` and `web;py` to see what happens.

**Comment by original-birdman** [comment]
OK.
You're right.
Putting the latest  `epg.py`, `services.py` and `web.py` in place makes it run as it used to do.

But I can still see no reason why you would wish to _change_ the API by adding an `endTime` parameter to `epgbouquet` when `epgmulti` already provides that interface. That is just confusing.
